// <auto-generated />
using System;
using PortlinkApp.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PortlinkApp.Core.Migrations
{
    [DbContext(typeof(ApprenticeDbContext))]
    [Migration("20251130214851_PortlinkInitial")]
    partial class PortlinkInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PortlinkApp.Core.Entities.Berth", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BerthCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Facilities")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("MaxDraft")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("MaxVesselLength")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TerminalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("BerthCode")
                        .IsUnique();

                    b.ToTable("Berths");
                });

            modelBuilder.Entity("PortlinkApp.Core.Entities.PortCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualTimeOfArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualTimeOfDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("BerthId")
                        .HasColumnType("integer");

                    b.Property<string>("CargoDescription")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("CargoQuantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("CargoUnit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DelayReason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("EstimatedTimeOfArrival")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EstimatedTimeOfDeparture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int?>("PriorityLevel")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VesselId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BerthId");

                    b.HasIndex("EstimatedTimeOfArrival");

                    b.HasIndex("VesselId", "Status");

                    b.ToTable("PortCalls");
                });

            modelBuilder.Entity("PortlinkApp.Core.Entities.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgentEmail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Beam")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("CargoType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Draft")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("FlagCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("LengthOverall")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OwnerCompany")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("VesselType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImoNumber")
                        .IsUnique();

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("PortlinkApp.Core.Entities.PortCall", b =>
                {
                    b.HasOne("PortlinkApp.Core.Entities.Berth", "Berth")
                        .WithMany("PortCalls")
                        .HasForeignKey("BerthId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PortlinkApp.Core.Entities.Vessel", "Vessel")
                        .WithMany("PortCalls")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Berth");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("PortlinkApp.Core.Entities.Berth", b =>
                {
                    b.Navigation("PortCalls");
                });

            modelBuilder.Entity("PortlinkApp.Core.Entities.Vessel", b =>
                {
                    b.Navigation("PortCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
